# Generated by Django 2.0.5 on 2018-07-09 01:51

from django.db import migrations
from contextlib import suppress


class Migration(migrations.Migration):

    dependencies = [
        ('joyous', '0005_auto_20180522_1158'),
    ]
    with suppress(ImportError):
        __import__("django.contrib.auth.migrations."
                   "0011_update_proxy_permissions")
        dependencies.append(('auth', '0011_update_proxy_permissions'))

    operations = [
        migrations.CreateModel(
            name='GeneralCalendarPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('joyous.calendarpage',),
        ),
        migrations.CreateModel(
            name='SpecificCalendarPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('joyous.calendarpage',),
        ),
    ]
