# Generated by Django 2.0.7 on 2018-09-20 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joyous', '0010_auto_20180920_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarpage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='joyous_calendarpage_set', serialize=False, to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='cancellationpage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='joyous_cancellationpage_set', serialize=False, to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='extrainfopage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='joyous_extrainfopage_set', serialize=False, to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='grouppage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='joyous_grouppage_set', serialize=False, to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='multidayeventpage',
            name='group_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joyous_multidayeventpage_set', to='joyous.GroupPage'),
        ),
        migrations.AlterField(
            model_name='multidayeventpage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='joyous_multidayeventpage_set', serialize=False, to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='recurringeventpage',
            name='group_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joyous_recurringeventpage_set', to='joyous.GroupPage'),
        ),
        migrations.AlterField(
            model_name='recurringeventpage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='joyous_recurringeventpage_set', serialize=False, to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='simpleeventpage',
            name='group_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joyous_simpleeventpage_set', to='joyous.GroupPage'),
        ),
        migrations.AlterField(
            model_name='simpleeventpage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='joyous_simpleeventpage_set', serialize=False, to='wagtailcore.Page'),
        ),
    ]
