# Generated by Django 4.2.9 on 2024-02-05 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("joyous", "0017_extcancellationpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouppage",
            name="page_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(model_name)s",
                serialize=False,
                to="wagtailcore.page",
            ),
        ),
    ]
